### 1. Imports para uso do NumPy

In [1]:
# Caso fosse necessário fazer a instalação (não precisa, estamos no anaconda)
# !pip install -q numpy=2.3.2

In [2]:
# Importação do Numpy
import numpy as np
import math
import time

### 2. Comparação do Python Puro com o Numpy

In [5]:
# Criação de uma lista com Numpy de 10 milhões de itens
precos_np = np.random.rand(10_000_000)
type(precos_np)

numpy.ndarray

In [11]:
# Criação de uma lista com Python Puro
precos_list = list(precos_np)
type(precos_list)

list

In [12]:
# Medindo o tempo inicial
t0 = time.time()
# Aplicando Operações no vetor np
desc = precos_np * 0.90
final = desc + 5
raiz = np.sqrt(precos_np)
# Exibição do tempo de processamento
print("Numpy: ", time.time() - t0, "segundos")

Numpy:  0.8345251083374023 segundos


In [18]:
# Medindo o tempo inicial
t0 = time.time()
# Aplicando Operações na lista python
desc = [p * 0.90 for p in precos_list]
final = [p + 5 for p in desc]
raiz = [math.sqrt(p) for p in precos_list]
# Exibição do tempo de processamento
print("Python puro: ", time.time() - t0, "segundos")

Python puro:  3.6082539558410645 segundos


### 3. Criação de Arrays Numpy

#### 3.1 Criação de um Array - Vetor

In [19]:
# Cria um array numpy a partir de uma lista Python
vector = np.array([17, 21, 100, 34])
print("\nVetor (Array 1D):\n")
print(vector)


Vetor (Array 1D):

[ 17  21 100  34]


#### 3.2 Atributos do Array

In [20]:
print("Formato (shape) do vetor: ", vector.shape)
print("Número de dimensões (ndim) do vetor: ", vector.ndim)
print("Número total de elementos (size) do vetor: ", vector.size)

Formato (shape) do vetor:  (4,)
Número de dimensões (ndim) do vetor:  1
Número total de elementos (size) do vetor:  4


#### 3.3 Criação de um Array - Vetor

In [21]:
# Cria um array numpy a partir de uma lista de listas
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print("\nMatriz (Array 2D):\n")
print(matriz)


Matriz (Array 2D):

[[1 2 3]
 [4 5 6]]


#### 3.4 Atributos do Array Matriz

In [31]:
print("Formato (shape) da matriz: ", matriz.shape)             # (linnhas, colunas)
print("Número de dimensões (ndim) da matriz: ", matriz.ndim)
print("Número total de elementos (size) da matriz: ", matriz.size)

Formato (shape) da matriz:  (2, 3)
Número de dimensões (ndim) da matriz:  2
Número total de elementos (size) da matriz:  6


#### 3.5 Criação de um Array - Tensor

In [32]:
# Cria um array numpu de mais de 2 dimensões (3D, 4D,...)
arr = np.arange(24).reshape(4, 3, 2)
print("\nArray (Array 3D):\n")
print(arr)


Array (Array 3D):

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


Aqui o arange recebe a quantidade de elementos do array e o reshape define as dimensõses dele os parâmetros são os eixos X, Y e Z

#### 3.6 Atributos do Tensor

In [33]:
print("Formato (shape) do tensor: ", arr.shape)             
print("Número de dimensões (ndim) do tensor: ", arr.ndim)
print("Número total de elementos (size) do tensor: ", arr.size)

Formato (shape) do tensor:  (4, 3, 2)
Número de dimensões (ndim) do tensor:  3
Número total de elementos (size) do tensor:  24


Um array com três dimensões vai ter um shape formado por profundidade, linhas e colunas, ou então altura, largura e profundidade em imagens.

#### 3.7 Criação de um Array - Tensor 4D

In [35]:
tensor4d = np.arange(120).reshape(2, 3, 4, 5)
print(tensor4d)

[[[[  0   1   2   3   4]
   [  5   6   7   8   9]
   [ 10  11  12  13  14]
   [ 15  16  17  18  19]]

  [[ 20  21  22  23  24]
   [ 25  26  27  28  29]
   [ 30  31  32  33  34]
   [ 35  36  37  38  39]]

  [[ 40  41  42  43  44]
   [ 45  46  47  48  49]
   [ 50  51  52  53  54]
   [ 55  56  57  58  59]]]


 [[[ 60  61  62  63  64]
   [ 65  66  67  68  69]
   [ 70  71  72  73  74]
   [ 75  76  77  78  79]]

  [[ 80  81  82  83  84]
   [ 85  86  87  88  89]
   [ 90  91  92  93  94]
   [ 95  96  97  98  99]]

  [[100 101 102 103 104]
   [105 106 107 108 109]
   [110 111 112 113 114]
   [115 116 117 118 119]]]]


#### 3.8 Atributos de um Tensor 4D

In [36]:
print("Formato (shape) do tensor: ", tensor4d.shape)             
print("Número de dimensões (ndim) do tensor: ", tensor4d.ndim)
print("Número total de elementos (size) do tensor: ", tensor4d.size)

Formato (shape) do tensor:  (2, 3, 4, 5)
Número de dimensões (ndim) do tensor:  4
Número total de elementos (size) do tensor:  120


In [ ]:
Aqui nós temos 2x3x4x5 (2 bloos, 3 planos, 4 linhas e 5 colunas)