### 4. Tipos de Dados Numpy

In [8]:
import numpy as np

In [9]:
# Numpy infere o tipo de dado automaticamente
arr_inteiros = np.array([1, 2, 3])
print("Tipo de dado (inteiros): ", arr_inteiros.dtype)

Tipo de dado (inteiros):  int64


In [10]:
arr_float = np.array([1.0, 2.0, 3.0])
print("Tipo de dado (float): ", arr_float.dtype)

Tipo de dado (float):  float64


#### 4.1 Informando o tipo de dado da estrutura

In [32]:
arr_float = np.array([1, 2, 3], dtype = np.float64)
print(arr_float)
print(arr_float.dtype)

[1. 2. 3.]
float64


#### 4.2 Convertendo dados com astype

In [6]:
arr_int = arr_float.astype(np.int32)
print(arr_int.dtype)

int32


#### 4.3 Indexação e Fatiamento de Estruturas de Dados do Numpy

In [7]:
# Criando uma MATRIZ 4x4 com números de 0 até o 15
data = np.arange(16).reshape(4, 4)
print("\nMatriz Origial:\n")
print(data)


Matriz Origial:

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#### 4.4 Fatiamento

In [31]:
# Obtendo um único elemento
print("Seleção de um elemento")
elemento = data[3, 3]
print(elemento)

print()

print("Fatiamento da primeira linha")
# Fatiamento obtendo TODOS os elementos da linha de indice 0
linha_0 = data[0]
print(linha_0)

print()

print("Indexação de todas as colunas da linha 0")
# Fatiamento obtendo TODOS os elementos da linha de indice 0 usando a sintaxe de colunas
linha_0_all = data[0, :]
print(linha_0_all)

print()

print("Indexação de todas as linhas da coluna 3")
# Fatiamento obtendo TODAS as linhas da coluna 3
col_3_all_lines = data[:, 3]
print(col_3_all_lines)

print()

print("Indexação de sub matriz")
# Bloco 2x2 INFERIOR DIREITO (10, 11, 14, 15)
block_inf_right = data[2:, 2:]
print(block_inf_right)

print()

# Indexação Booleana
print("Indexação com booleano")
greather_than_10 = data[data > 10]
print(greather_than_10)

Seleção de um elemento
15

Fatiamento da primeira linha
[0 1 2 3]

Indexação de todas as colunas da linha 0
[0 1 2 3]

Indexação de todas as linhas da coluna 3
[ 3  7 11 15]

Indexação de sub matriz
[[10 11]
 [14 15]]

Indexação com booleano
[11 12 13 14 15]


Dada a matriz 5x5 abaixo, vamos criar um novo array que contenha apenas as linhas de índice par e as colunas de índice ímpar.

In [33]:
# Cria a matriz 5x5
matriz = np.arange(25).reshape(5, 5)

In [34]:
# Usando start:stop:step
resultado = matriz[::2, 1::2]
print("Matriz Original\n")
print(matriz)
print()
print("Matriz Nova")
print(resultado)
print()

Matriz Original

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Matriz Nova
[[ 1  3]
 [11 13]
 [21 23]]

