### 5. Operações Matemáticas Vetorizadas com NumPy

In [1]:
import numpy as np

In [2]:
# Simulando dados de preços de produtos
precos = np.array([19.99, 25.50, 8.90, 43.00])
print(f"\nPreços Originais: {precos}\n")


Preços Originais: [19.99 25.5   8.9  43.  ]



In [4]:
# Aplicando o desconto de 10%
precos_com_desconto = precos * 0.90
print(f"\nPreços com 10% de desconto: {precos_com_desconto}")


Preços com 10% de desconto: [17.991 22.95   8.01  38.7  ]


O mesmo resultado obtido aqui poderia ter sido feito com Python puro, entretanto, a velocidade de operações utilizando o numpy é bem maior do que no próprio Python.

### 6. Agregações Estatísticas com NumPy

In [6]:
# Simulando as notas de 3 alunos em 4 provas
notas = np.array([
    [8.5, 7.0, 9.2, 6.5],
    [5.5, 6.8, 7.5, 8.0],
    [9.5, 9.0, 8.8, 10.0]
])
print("Matriz de Notas\m")
print(notas)

Matriz de Notas\m
[[ 8.5  7.   9.2  6.5]
 [ 5.5  6.8  7.5  8. ]
 [ 9.5  9.   8.8 10. ]]


In [ ]:
# Fazendo as agregações estatísticas na matriz de notas

print(f"Média geral da turma: {notas.mean():.2f}")
print(f"Nota máxima da turma: {notas.max():.2f}")
print(f"Nota mínima da turma: {notas.min():.2f}")
print(f"Soma de todas as notas da turma: {notas.sum():.2f}")

print(notas.dtype)

Média geral da turma: 8.03
Nota máxima da turma: 10.00
Nota mínima da turma: 5.50
Soma de todas as notas da turma: 96.30
float64


In [11]:
# Agregação - Estatística em um único eixo

# Faz a média por eixo e arredonda para duas casas decimais.
media_por_aluno = notas.mean(axis=1).round(2)
print(media_por_aluno)

# Agregação no nível de linha
media_por_prova = notas.mean(axis=0).round(2)
print(media_por_prova)

[7.8  6.95 9.32]
[7.83 7.6  8.5  8.17]


### 7. Broadcasting

Broadcasting basicamente é realizar operações matemáticas entre arrays sem necessidade de criar cópias na memória.

In [13]:
# Matriz 3x3
matriz = np.array([
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9]
])
type(matriz)

numpy.ndarray

In [14]:
matriz.shape

(3, 3)

In [16]:
# Vetor 1D com 3 elementos
vetor = np.array([10, 20, 30])
type(vetor)
vetor.shape

(3,)

Somando os valores do vetor aos valores de CADA linha da matriz

In [19]:
# Resultado
resultado = matriz + vetor

print(f"Matriz Original:\n{matriz}\n")
print(f"Vetor Original: {vetor}\n")
print(f"Matriz Alterada:\n{resultado}\n")

print(f"Dimensões da nova matriz: {resultado.shape}")

Matriz Original:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Vetor Original: [10 20 30]

Matriz Alterada:
[[11 22 33]
 [14 25 36]
 [17 28 39]]

Dimensões da nova matriz: (3, 3)


Criando uma matriz de produtos para relacionar com um vetor de bônus

In [21]:
# Matriz de faturamento de 3 produtos em 4 meses
faturamento = np.array([
    [100, 110, 120, 130],
    [200, 210, 220, 230],
    [300, 310, 320, 330]
])
print(f"{faturamento}\n{faturamento.shape}")

[[100 110 120 130]
 [200 210 220 230]
 [300 310 320 330]]
(3, 4)


In [22]:
# Vetor com bônus (incentivos) para cada produto
bonus_por_produto = np.array([5, 10, 15])
type(bonus_por_produto)

numpy.ndarray

Queremos adicionar um bônus a cada valor de faturamento, por linha. Ou seja, todos os itens da primeira linha devem receber o bônus de 5, por exemplo, e assim por diante.

In [26]:
# OCORRE UM ERRO DE RESHAPE - POIS AS DIMENSÕES SÃO DIFERENTES !
# faturamento_com_bonus = faturamento + bonus_por_produto

Consertando o problema de shape nas operações com matrizes de dimensões diferentes.

In [29]:
print(bonus_por_produto.shape)
bonus_formatado = bonus_por_produto.reshape(3, 1)
print(bonus_formatado.shape)

(3,)
(3, 1)


In [31]:
# Faturamento com Bônus 
faturamento_com_bonus = faturamento + bonus_formatado
print(faturamento_com_bonus)

[[105 115 125 135]
 [210 220 230 240]
 [315 325 335 345]]


#### 8. Manipulação de Formato de Arrays

Muitas vezes precisamos reorganizar os dados em um formato diferente para a análise ou para alimentar um modelo de IA.

In [32]:
# Criando um array 1D com 12 elementos
dados_sequenciais = np.arange(12)
print(f"\nArray Original (1D): {dados_sequenciais}\n")


Array Original (1D): [ 0  1  2  3  4  5  6  7  8  9 10 11]



In [33]:
# Transformando o vetor 1D em uma matriz
matriz_3x4 = dados_sequenciais.reshape(3, 4)
print(f"Matriz\n{matriz_3x4}")

Matriz
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [35]:
# Obtendo a matriz transposta
print(matriz_3x4.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [37]:
# Achatando novamente a matriz para a forma de vetor
vetor_novamente = matriz_3x4.flatten()
print(vetor_novamente)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
